### ISSUE TITLE
Unable to launch CMS on localhost

### ISSUE THREAD

**Issue by nalmeida** [plentico/plenti#278]
Hi, 

I did a fresh install / site usinig plenti but I am not able to launch the "cms login" running on localhost.
I am facing the following error:

```js
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': Nodes of type '#text' may not be inserted inside nodes of type '#document'.
    at append (http://localhost:3000/spa/web_modules/svelte/internal/index.mjs:288:20)
    at insert (http://localhost:3000/spa/web_modules/svelte/internal/index.mjs:300:9)
    at Object.m (http://localhost:3000/spa/core/router.js:1:934)
    at mount_component (http://localhost:3000/spa/web_modules/svelte/internal/index.mjs:1598:26)
    at init (http://localhost:3000/spa/web_modules/svelte/internal/index.mjs:1690:9)
    at new Component (http://localhost:3000/spa/core/router.js:1:3239)
    at http://localhost:3000/spa/core/main.js:1:33
```

## Commands performed

```sh
$ plenti new site plenti-teste
$ cd plenti-teste
$ npm install # no sure if is necessary, did it just in case
$ plenti serve
```
I am able to access the website on `http://localhost:3000`

I am able to change some content on VSCode and see it on the browser (`content/_index.json`)

Other than that, I did not perform any change /config and I was expecting to have the "admin" interface running on localhost.

Using:
- MacOS: `Ventura 13.2`
- Plenti: `v0.6.7`
- Node: `v16.19.0`
- NPM: `8.19.3`

**Comment by jimafisk** [comment]
The `Failed to execute 'insertBefore'` is due to adding configurable entrypoints via https://github.com/plentico/plenti/issues/211. It shouldn't prevent the CMS from working, but is something I plan on reverting in the near future to clear out the console errors and stop the site from flickering on load. There seems to be a bug with hydrating dynamic svelte components.

If you go to the http://localhost:3000/admin page and click the "login" button there, does it give you an admin toolbar? Thanks!

**Comment by jimafisk** [comment]
Oh wait, I know what's happening here... Sorry this is my fault, I hastily updated the API before a talk I gave on Friday and didn't update the "starter" scaffolding code.

Basically what's happening is we removed the `adminMenu` prop because that's now included in the `user` prop. So in `layouts/global/html.svelte` you should change:

```svelte
export let content, layout, allContent, allLayouts, env, user, adminMenu;
```

To:

```svelte
export let content, layout, allContent, allLayouts, env, user;
```

and

```svelte
{#if user && $user.isAuthenticated}
  <svelte:component this={adminMenu} {user} bind:content={content} />
{/if}
```

To:

```svelte
{#if user && $user.isAuthenticated}
  <svelte:component this={$user.menu} {user} bind:content={content} />
{/if}
```

Does that work?

**Comment by nalmeida** [comment]
**🎉 YES 🎉** it is working!

The original JS error still on console `...Failed to execute 'insertBefore' on 'Node':...` but the admin is Working!

I was able to change content on pages and and also creating a new page! 

I believe this fix should be applied on the repo.

**Comment by jimafisk** [comment]
Awesome :guitar: 

I just pushed a fix for this and I'll create a new release shortly. 

I can fix the console error as well by removing the configurable entrypoint (https://github.com/plentico/plenti/issues/211). It would have been nice to keep that feature, but the console error and hydration flicker probably aren't worth the added benefit.

**Comment by nalmeida** [comment]
Tks for the support @jimafisk!

**Comment by jimafisk** [comment]
The starter scaffolding should be fixed in [v0.6.8](https://github.com/plentico/plenti/releases/tag/v0.6.8).
