### ISSUE TITLE
plenti serve is spitting errors

### ISSUE THREAD

**Issue by 174414-Rodda** [plentico/plenti#290]
Hi there newbie here.

I installed plenti using [this](https://github.com/plentico/plenti/issues/283). I am running Linux pop-os 6.2.6-76060206-generic #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux and fish as my shell.plenti new site name is working.  I am using plenti v0.6.27

But when I tried plenti serve the following is the output:

~~~fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f9587554ef4]

runtime stack:
runtime.throw({0x1b292ba?, 0x0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/signal_unix.go:802 +0x389

goroutine 7 [syscall]:
runtime.cgocall(0x9a7730, 0xc00004e598)
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/cgocall.go:157 +0x5c fp=0xc00004e570 sp=0xc00004e538 pc=0x41289c
net._C2func_getaddrinfo(0xc00017bdd0, 0x0, 0xc0001d7ec0, 0xc000010800)
        _cgo_gotypes.go:94 +0x56 fp=0xc00004e598 sp=0xc00004e570 pc=0x6267f6
net.cgoLookupIPCNAME.func1({0xc00017bdd0, 0x0?, 0x0?}, 0xc00017bc80?, 0x62ce3b?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/cgo_unix.go:160 +0x9f fp=0xc00004e5f0 sp=0xc00004e598 pc=0x62851f
net.cgoLookupIPCNAME({0x1b0adbc, 0x3}, {0xc00017bc80, 0x9})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/cgo_unix.go:160 +0x16d fp=0xc00004e738 sp=0xc00004e5f0 pc=0x627d8d
net.cgoIPLookup(0x380ab30?, {0x1b0adbc?, 0xc00017bc90?}, {0xc00017bc80?, 0x0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/cgo_unix.go:217 +0x3b fp=0xc00004e7a8 sp=0xc00004e738 pc=0x6285db
net.cgoLookupIP.func1()
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/cgo_unix.go:227 +0x36 fp=0xc00004e7e0 sp=0xc00004e7a8 pc=0x628a16
runtime.goexit()
        /opt/hostedtoolcache/go/1.18.10/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00004e7e8 sp=0xc00004e7e0 pc=0x472ce1
created by net.cgoLookupIP
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/cgo_unix.go:227 +0x12a

goroutine 1 [select]:
net.(*Resolver).lookupIPAddr(0x380ab20, {0x27f8598?, 0xc000026120}, {0x1b0adbc, 0x3}, {0xc00017bc80, 0x9})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/lookup.go:325 +0x51b
net.(*Resolver).internetAddrList(0x27f8598?, {0x27f8598?, 0xc000026120?}, {0x1b0adbc, 0x3}, {0xc00017bc80?, 0xe?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0xc000026120?, {0x27f8598, 0xc000026120}, {0x1b0b323, 0x4}, {0x1b0adbc?, 0x0?}, {0xc00017bc80, 0xe}, {0x0, ...})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc0001338c0, {0x27f8598, 0xc000026120}, {0x1b0adbc, 0x3}, {0xc00017bc80, 0xe})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/dial.go:406 +0x448
net.(*Dialer).Dial(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/dial.go:351
net.Dial({0x1b0adbc?, 0xc?}, {0xc00017bc80?, 0x1?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/dial.go:319 +0x7a
github.com/plentico/plenti/cmd.checkPortAvailability(0xc00017bc66?)
        /home/runner/work/plenti/plenti/cmd/serve.go:45 +0x7f
github.com/plentico/plenti/cmd.glob..func6(0x37b0600?, {0xc0001dd1a0, 0x0, 0x1})
        /home/runner/work/plenti/plenti/cmd/serve.go:94 +0x156
github.com/spf13/cobra.(*Command).execute(0x37b0600, {0xc0001dd190, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x37b0380)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/plentico/plenti/cmd.Execute()
        /home/runner/work/plenti/plenti/cmd/root.go:48 +0x25
main.main()
        /home/runner/work/plenti/plenti/main.go:7 +0x17

goroutine 6 [select]:
net.cgoLookupIP({0x27f8560, 0xc0001e4680}, {0x1b0adbc, 0x3}, {0xc00017bc80, 0x9})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/cgo_unix.go:228 +0x1aa
net.(*Resolver).lookupIP(0x380ab20, {0x27f8560, 0xc0001e4680}, {0x1b0adbc, 0x3}, {0xc00017bc80, 0x9})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/lookup_unix.go:96 +0x128
net.glob..func1({0x27f8560?, 0xc0001e4680?}, 0x0?, {0x1b0adbc?, 0x0?}, {0xc00017bc80?, 0x0?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/lookup.go:319 +0x9f
internal/singleflight.(*Group).doCall(0x380ab30, 0xc000100f50, {0xc00017bc90, 0xd}, 0x0?)
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
        /opt/hostedtoolcache/go/1.18.10/x64/src/internal/singleflight/singleflight.go:88 +0x2ec
~~~

Did I messup the install? Please help

**Comment by 174414-Rodda** [comment]
I uninstalled it and using the 0.6.13, It is working. Thank you

**Comment by 174414-Rodda** [comment]
I was able to run the file, but I got the following warning.
```

deploy
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, JamesIves/github-pages-deploy-action@releases/v3. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

I am using [this](https://github.com/plenti-themes/compendium) Where/how to find the deployed pages link.

**Comment by jimafisk** [comment]
Can you send me a link to your project? It sounds like you're using an old version of NodeJS in your CI build process. In your `.github/workflows/gh-pages.yml` you probably want something like:

```yml
- name: Setup Node
  uses: actions/setup-node@v2-beta
  with:
    node-version: '20'
```

Just note this is likely a Node / NPM issue, not Plenti specific. I unfortunately do not have a ton of excess capacity to help debug third party scripts / libraries.

**Comment by 174414-Rodda** [comment]
Sorry for late reply, please take a look at the following repository:[this one](https://github.com/prohtmlcoder/website)

I tweaked some stuff from the compendium report.
 - Build It
 - Committed it to the above mentioned repo
 - I made few changes to github actions as well


Thank you once again

**Comment by jimafisk** [comment]
Hi @174414-Rodda, it looks like the repository you referenced has been removed. If you still need help with anything, please just let me know! Thanks!

**Comment by jimafisk** [comment]
Hi @174414-Rodda, I haven't heard back on this ticket so I'm closing for now. If there's anything I can help with, feel free to re-open. Thank you!
