### ISSUE TITLE
Broken CI builds because of missing node_modules

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#70]
Example: https://github.com/plentico/plenti.co/runs/1215498410?check_suite_focus=true#step:4:6

Errors:
```
Can't read node_modules/svelte/compiler.js: open node_modules/svelte/compiler.js: no such file or directoryCan't read node_modules/svelte/animate/index.js: open node_modules/svelte/animate/index.js: no such file or directoryCould not add create_ssr_component() func from svelte/internal: <nil>Can't read node_modules/svelte/easing/index.js: open node_modules/svelte/easing/index.js: no such file or directoryCould not add create_ssr_component() func from svelte/internal: <nil>Can't read node_modules/svelte/internal/index.js: open node_modules/svelte/internal/index.js: no such file or directoryCould not add create_ssr_component() func from svelte/internal: <nil>Can't read node_modules/svelte/motion/index.js: open node_modules/svelte/motion/index.js: no such file or directoryCould not add create_ssr_component() func from svelte/internal: <nil>Can't read node_modules/svelte/store/index.js: open node_modules/svelte/store/index.js: no such file or directoryCould not add create_ssr_component() func from svelte/internal: <nil>Can't read node_modules/svelte/transition/index.js: open node_modules/svelte/transition/index.js: no such file or directoryCould not add create_ssr_component() func from svelte/internal: <nil>V8go could not execute js.code: TypeError: Cannot read property 'code' of undefinedTotal 
```

And:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa1ff32]

goroutine 1 [running]:
rogchap.com/v8go.(*Value).String.func1(0x0, 0x0)
	/home/runner/go/pkg/mod/rogchap.com/v8go@v0.2.0/value.go:20 +0x22
rogchap.com/v8go.(*Value).String(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/rogchap.com/v8go@v0.2.0/value.go:20 +0x48
plenti/cmd/build.compileSvelte(0xc000088d90, 0xc000088dc0, 0x172193b, 0x15, 0xc0000c3900, 0x1c, 0xc0000c38c0, 0x15)
	/home/runner/work/plenti/plenti/cmd/build/client.go:125 +0x2ad
plenti/cmd/build.Client(0xc0000a2bc0, 0x6)
	/home/runner/work/plenti/plenti/cmd/build/client.go:77 +0x688
plenti/cmd.Build()
	/home/runner/work/plenti/plenti/cmd/build.go:107 +0x500
plenti/cmd.glob..func1(0x2294380, 0x2322570, 0x0, 0x0)
	/home/runner/work/plenti/plenti/cmd/build.go:46 +0x20
github.com/spf13/cobra.(*Command).execute(0x2294380, 0x2322570, 0x0, 0x0, 0x2294380, 0x2322570)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x2293900, 0x7383ba, 0x22a6700, 0xc000000180)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
plenti/cmd.Execute()
	/home/runner/work/plenti/plenti/cmd/root.go:44 +0x31
main.main()
	/home/runner/work/plenti/plenti/main.go:8 +0x20
```

**Comment by jimafisk** [comment]
Needed to pull the generated defaults from the new location (we're sharing node_modules for both the new v8go build and the legacy nodejs build).
