### ISSUE TITLE
Nicer error messages

### ISSUE THREAD

**Issue by jimafisk** [plentico/plenti#73]
If you try to run a command like `plenti serve` outside of an actual plenti project, you'll get an error like this:

<details>
<summary>Screenshot</summary>

![nicer_errors](https://user-images.githubusercontent.com/5913244/95785663-2895ae00-0ca4-11eb-8ed3-79c0198e87c1.png)

</details>

```
Unable to read site config file: unexpected end of JSON input
Unable to read site config file: unexpected end of JSON input
Total build took 135.69668ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa4dfa0]

goroutine 1 [running]:
plenti/cmd/build.Client.func1(0x17194f7, 0x6, 0x0, 0x0, 0x1af32e0, 0xc00007be60, 0x2, 0x2)
	/home/jimafisk/Projects/jantcu/plentico/plenti/cmd/build/client.go:84 +0x110
path/filepath.Walk(0x17194f7, 0x6, 0xc0005e5988, 0x15, 0xc000022520)
	/usr/local/go/src/path/filepath/path.go:404 +0x6a
plenti/cmd/build.Client(0xc00050c1a8, 0x6)
	/home/jimafisk/Projects/jantcu/plentico/plenti/cmd/build/client.go:80 +0x741
plenti/cmd.Build()
	/home/jimafisk/Projects/jantcu/plentico/plenti/cmd/build.go:107 +0x500
plenti/cmd.glob..func1(0x228dba0, 0x231c4e8, 0x0, 0x0)
	/home/jimafisk/Projects/jantcu/plentico/plenti/cmd/build.go:46 +0x20
plenti/cmd.glob..func5(0x228dba0, 0x231c4e8, 0x0, 0x0)
	/home/jimafisk/Projects/jantcu/plentico/plenti/cmd/serve.go:56 +0x548
github.com/spf13/cobra.(*Command).execute(0x228dba0, 0x231c4e8, 0x0, 0x0, 0x228dba0, 0x231c4e8)
	/home/jimafisk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x228d900, 0x737b4a, 0x22a06e0, 0xc000000180)
	/home/jimafisk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jimafisk/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
plenti/cmd.Execute()
	/home/jimafisk/Projects/jantcu/plentico/plenti/cmd/root.go:44 +0x31
main.main()
	/home/jimafisk/Projects/jantcu/plentico/plenti/main.go:8 +0x20
```

This indeed should not work, but it would be better to offer some helpful information to the user to give some direction on how to fix the problem. Something like: `It doesn't look like you're inside a valid Plenti project. Please create one or fix your app structure before trying to run this command again.`

**Comment by jimafisk** [comment]
Each step of the build process (`cmd/client.go`, `cmd/data_source.go`, etc) attempts to walk specific directories to get file information. If run outside of an actually project, it panics and throws the error above. I added a `defer func()` to recover the panic using the method outlined here: https://medium.com/swlh/simple-guide-to-panic-handling-and-recovery-in-golang-72d6181ae3e8#:~:text=Recover%20is%20a%20function%20provided,will%20capture%20the%20panic%20value.
